version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: messenger_user
      POSTGRES_PASSWORD: messenger_password
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messenger_user -d messenger_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://messenger_user:messenger_password@postgres:5432/messenger_db
      - SECRET_KEY=your-super-secret-jwt-key-change-this
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

volumes:
  postgres_data:
